# DataSource Config
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://123.206.81.22:3306/eblog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    url: jdbc:p6spy:mysql://123.206.81.22:3306/eblog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Mzx@123456
#    password: 123456
#    passwo
    mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml
  freemarker:
    cache: false
  redis:
    password: Mzx@123456
    host: 123.206.81.22
    port: 6379
